[build]
publish = "public"
command = "git submodule update --init --recursive --depth 1 && make production-build"

[build.environment]
HUGO_VERSION = "0.79.0"
NODE_VERSION = "12"

[context.deploy-preview]
command = "git submodule update --init --recursive --depth 1 && make preview-build"

[context.branch-deploy]
command = "git submodule update --init --recursive --depth 1 && make preview-build"
